steps:
  # Dockerイメージのビルド
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_JOB_NAME}:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_JOB_NAME}:latest'
      - '.'

  # イメージをArtifact Registryにプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_JOB_NAME}'

  # Cloud Run Jobへデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'jobs'
      - 'deploy'
      - '${_JOB_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_JOB_NAME}:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--memory'
      - '2Gi'
      - '--task-timeout'
      - '600'
      - '--max-retries'
      - '1'
      - '--parallelism'
      - '1'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--set-secrets'
      - 'NOBILIST_EMAIL=nobilist-email:latest,NOBILIST_PASSWORD=nobilist-password:latest,SPREADSHEET_ID=spreadsheet-id:latest,SLACK_WEBHOOK_URL=slack-webhook-url:latest'
      - '--update-secrets'
      - 'GOOGLE_CREDENTIALS_PATH=/secrets/google-credentials:google-credentials:latest'

# 環境変数の設定
substitutions:
  _JOB_NAME: nobilist-rank-check-job
  _REGION: asia-northeast1
  _REPOSITORY: nobilist-repo

# ビルドのオプション
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'